concourse-db:
  image: postgres:9.5
  environment:
    POSTGRES_DB: concourse
    POSTGRES_PASSWORD: concourse_pass
    POSTGRES_USER: concourse_user
    PGDATA: /database
concourse-web:
  image: gregoryarcara/concourse-bin:1.5.1
  links:
    - concourse-db
  command: /root/scripts/start.sh web
  ports:
    - "8080:8080"
  environment:
    CONCOURSE_LOGIN: 'concourse'
    CONCOURSE_PASSWORD: 'password'
    CONCOURSE_EXTERNAL_URL: 'http://192.168.99.100:8080/'
concourse-worker:
  image: gregoryarcara/concourse-bin:1.5.1
  privileged: true
  links:
    - concourse-web
    - concourse-db
  command: /root/scripts/start.sh worker
